spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/investment_assets
    username: postgres
    password: postgres

  flyway:
    enabled: true
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

issmoex:
  api:
    url: http://iss.moex.com/iss
    serviceName: moex

