spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/investment_assets
    username: postgres
    password: postgres

  flyway:
    enabled: true

issmoex:
  api:
    url: https://iss.moex.com/iss
    serviceName: moex

